- name: This playbook will install, configure and deploy custom html page into nginx web server.
  hosts: ubuntu
  gather_facts: yes
  vars:
    - greeting_msg: DevOps!
    - provisioner_tool: Docker
    - conf_mgr_tool: Ansible
  tasks:
    - name: Install nginx web server into Ubuntu Ansible Node
      apt:  name=nginx state=latest update_cache=yes
      
    - name: Configure nginx web root folder in Ubuntu Ansible Node
      copy: src=default dest=/etc/nginx/sites-available/default backup=yes
      register: copy_status
      
    - debug: var=copy_status

    - name: Create the customized web root folder
      file: path=/var/html state=directory mode=0777

    - name: Retrieve IP address of the ansible node
      shell: hostname -i
      register: ip_addr
      - name: This playbook will install, configure and deploy custom html page into nginx web server.
      hosts: all
      gather_facts: yes
      vars:
        - greeting_msg: DevOps!
        - provisioner_tool: Docker
        - conf_mgr_tool: Ansible
      tasks:
        - name: Install nginx web server into Ubuntu Ansible Node
          when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
          apt:  name=nginx state=latest update_cache=yes
    
        - name: Fix the metalink issue in CentOS Ansible Node
          when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
          copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
    
        - name: Install Extra Packages for Enterprise Linux (EPEL) in CentOS Ansible Node
          when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
          yum:  name=epel-release state=latest
    
        - name: Install nginx web server into CentOS Ansible Node
          when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
          yum:  name=nginx state=latest
          
        - name: Configure nginx web root folder in Ubuntu Ansible Node
          when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
          copy: src=default dest=/etc/nginx/sites-available/default backup=yes
          register: copy_status
    
        - name: Configure nginx web root folder in CentOS Ansible Node
          when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
          copy: src=default.conf dest=/etc/nginx/conf.d/default.conf backup=yes
          register: copy_status
          
        - debug: var=copy_status
    
        - name: Create the customized web root folder
          file: path=/var/html state=directory mode=0777
    
        - name: Retrieve IP address of the ansible node
          shell: hostname -i
          register: ip_addr
    
        - name: Print the ip_addr register variablee
          debug: var=ip_addr
    
        - name: Deploy custom html web page into nginx on Ansible Node
          template: src=index.html.j2  dest=/var/html/index.html
    
        - name: Restart the nginx service in Ansible Node to apply config changes
          #Since service module has a bug related to docker, hence we are using command module
          #service: name=nginx state=started
          when: copy_status.changed ==  true    
          command: service nginx restart
    - name: Print the ip_addr register variablee
      debug: var=ip_addr

    - name: Deploy custom html web page into nginx on Ansible Node
      template: src=index.html.j2  dest=/var/html/index.html

    - name: Restart the nginx service in Ansible Node to apply config changes
      #Since service module has a bug related to docker, hence we are using command module
      #service: name=nginx state=started
      when: copy_status.changed ==  true    
      command: service nginx restart

- name: This playbook will install, configure and deploy custom html page into nginx web server.
  hosts: centos
  gather_facts: yes
  vars:
    - greeting_msg: DevOps!
    - provisioner_tool: Docker
    - conf_mgr_tool: Ansible
  tasks:
    - name: Fix the metalink issue in CentOS Ansible Node
      copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

    - name: Install Extra Packages for Enterprise Linux (EPEL) in CentOS Ansible Node
      yum:  name=epel-release state=latest

    - name: Install nginx web server into CentOS Ansible Node
      yum:  name=nginx state=latest
      
    - name: Configure nginx web root folder in CentOS Ansible Node
      copy: src=default.conf dest=/etc/nginx/conf.d/default.conf backup=yes
      register: copy_status
      
    - debug: var=copy_status

    - name: Create the customized web root folder
      file: path=/var/html state=directory mode=0777

    - name: Retrieve IP address of the ansible node
      shell: hostname -i
      register: ip_addr

    - name: Print the ip_addr register variablee
      debug: var=ip_addr

    - name: Deploy custom html web page into nginx on Ansible Node
      template: src=index.html.j2  dest=/var/html/index.html

    - name: Restart the nginx service in Ansible Node to apply config changes
      #Since service module has a bug related to docker, hence we are using command module
      #service: name=nginx state=started
      when: copy_status.changed ==  true    
      command: service nginx restart